var dolmensCN = [
{name:"Cista del Molí",municipi:"Eina",lat:42.48361,lon:2.07056,hi_es:"SI",megalith_type:"cist",wikipedia:"ca:Cista megalítica del Molí",wikidata:"Q62081840",source:"",alt_name:""},
{name:"Dolmen de la Borda",municipi:"Eina",lat:42.48541,lon:2.07431,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Borda",wikidata:"Q11917570",source:"",alt_name:"Dolmen dels Pasquerets"},
{name:"Dolmen de lo Pou",municipi:"Eina",lat:42.48111,lon:2.07944,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de lo Pou",wikidata:"Q16031938",source:"",alt_name:""},
{name:"Dolmen de Brangolí",municipi:"Enveig",lat:42.48194,lon:1.90528,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Brangolí",wikidata:"Q62096447",source:"",alt_name:""},
{name:"Arca de Calaons",municipi:"Catllà",lat:42.63389,lon:2.42194,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Arca de Calaons",wikidata:"Q11350549",source:"",alt_name:""},
{name:"Dolmen de la Font de l'Aram I",municipi:"Rià i Cirac",lat:42.63111,lon:2.36361,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen 1 de la Font de l'Aram",wikidata:"Q16031916",source:"",alt_name:"Dolmen del Roc de l'Home Mort II"},
{name:"Dolmen del Mas Lluçanes II",municipi:"Tarerac",lat:42.67333,lon:2.51086,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen 2 del Mas Lluçanes",wikidata:"Q16031925",source:"",alt_name:""},
{name:"Dolmen de Cobartorat",municipi:"Cornellà de Conflent i Fullà",lat:42.56761666,lon:2.366958653,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:dolmen de Cobartorat",wikidata:"Q11917558",source:"",alt_name:""},
{name:"Dolmen de la Font de l'Orri",municipi:"Eus",lat:42.67444,lon:2.43944,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Font de l'Orri",wikidata:"Q16031918",source:"",alt_name:"Dolmen del Coll del Trivi"},
{name:"Dolmen de la Lloseta",municipi:"Clarà i Villerac i els Masos",lat:42.60306,lon:2.45417,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Lloseta",wikidata:"Q51879094",source:"",alt_name:"Dolmen de la Barraca de la Llosa"},
{name:"Dolmen de les Falgueres de Baix",municipi:"Mosset",lat:42.63944,lon:2.36472,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Sant Ponci",municipi:"Molig",lat:42.65889,lon:2.40833,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Sant Ponci",wikidata:"Q16031952",source:"",alt_name:""},
{name:"Dolmen de Serra Mitjana",municipi:"Catllà",lat:42.65336,lon:2.43482,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Serra Mitjana",wikidata:"Q16031954",source:"",alt_name:""},
{name:"Dolmen del Molló",municipi:"Mosset",lat:42.68528,lon:2.34694,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Pla de l'Arca",municipi:"Molig",lat:42.67306,lon:2.40028,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Pla de l’Arca (Molig)",wikidata:"Q16031934",source:"",alt_name:""},
{name:"Dolmen del Prat Clos",municipi:"Rià i Cirac",lat:42.62667,lon:2.37861,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Prat Clos",wikidata:"Q52146335",source:"",alt_name:""},
{name:"Dolmen del Roc de l'Home Mort",municipi:"Conat",lat:42.63056,lon:2.37612,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Roc de l'Home Mort",wikidata:"Q56400634",source:"",alt_name:""},
{name:"Dolmen del Serrat d'en Perot",municipi:"Cornellà de Conflent",lat:42.58111,lon:2.38722,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat d'en Perot",wikidata:"Q16031961",source:"",alt_name:""},
{name:"Dolmen de la Serra de Santa Eulàlia I",municipi:"Fullà i Serdinyà",lat:42.56833,lon:2.34639,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dòlmens de la Serra de Santa Eulàlia",wikidata:"Q16031953",source:"",alt_name:"Dolmen de les Garberes I"},
{name:"Dolmen de la Serra de Santa Eulàlia II",municipi:"Fullà i Serdinyà",lat:42.56556,lon:2.34639,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dòlmens de la Serra de Santa Eulàlia",wikidata:"Q16031953",source:"",alt_name:"Dolmen de les Garberes II"},
{name:"Dolmen del Pla d'Arques I",municipi:"Escaró i Fullà",lat:42.54222,lon:2.33972,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dòlmens del Pla d'Arques",wikidata:"Q51845724",source:"",alt_name:""},
{name:"Dolmen del Pla d'Arques II",municipi:"Escaró i Fullà",lat:42.54639,lon:2.34333,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dòlmens del Pla d'Arques",wikidata:"Q51845724",source:"",alt_name:""},
{name:"Dolmen del Pla de Tarters II",municipi:"Serdinyà",lat:42.5599365,lon:2.3296688,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dòlmens del Pla de Tarters",wikidata:"Q16031936",source:"",alt_name:""},
{name:"Dolmen del Pla de Tarters I",municipi:"Serdinyà",lat:42.5598831,lon:2.3296938,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dòlmens del Pla de Tarters",wikidata:"Q16031936",source:"",alt_name:""},
{name:"Llosa del Cortal dels Polls",municipi:"Arboçols",lat:42.6663437,lon:2.4661133,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Llosa del Cortal dels Polls",wikidata:"Q16511346",source:"",alt_name:""},
{name:"Menhir de Catllà",municipi:"Catllà",lat:42.63556,lon:2.42139,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Roc de l'Amorriador",municipi:"Glorianes",lat:42.59009,lon:2.57805,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Roc de l'Amorriador",wikidata:"Q47183512",source:"",alt_name:"Cementiri dels Moros"},
{name:"Cova de l'Alarb",municipi:"Argelers",lat:42.52533,lon:3.03484,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Cova de l'Alarb (Argelers)",wikidata:"Q3001820",source:"",alt_name:""},
{name:"Dolmen dels Collets de Cotlliure",municipi:"Argelers",lat:42.52112,lon:3.03296,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen dels Collets de Cotlliure",wikidata:"Q15948639",source:"",alt_name:""},
{name:"Dolmen de Sant Pere dels Forquets",municipi:"Argelers",lat:42.51917,lon:3.02639,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Sant Pere dels Forquets",wikidata:"Q16031951",source:"",alt_name:""},
{name:"Cova de l'Alarb",municipi:"Banyuls de la Marenda",lat:42.46056,lon:3.05472,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Cova de l'Alarb (Banyuls de la Marenda)",wikidata:"Q16031912",source:"",alt_name:"Dolmen del Coll de Brau"},
{name:"Dolmen del Coll de les Portes",municipi:"Banyuls de la Marenda",lat:42.44667,lon:3.12361,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Coll de les Portes",wikidata:"Q16031907",source:"",alt_name:""},
{name:"Dolmen del Coll de la Llosa",municipi:"Bulaternera",lat:42.63056,lon:2.60583,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Coll de la Llosa",wikidata:"Q16031906",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:""},
{name:"Dolmen de les Rieres",municipi:"Bulaternera",lat:42.64472,lon:2.60778,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de les Rieres",wikidata:"Q20817388",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:"Dolmen del Camp Gran II"},
{name:"Dolmen de Caladroer II",municipi:"Caladroer",lat:42.73139,lon:2.65583,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Caladroer II",wikidata:"Q20821063",source:"",alt_name:""},
{name:"Dolmen de les Arques del Coll del Moro",municipi:"Cameles",lat:42.6325,lon:2.68028,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de les Arques del Coll del Moro",wikidata:"Q56402723",source:"",alt_name:""},
{name:"Dolmen del Serrat d'en Geli",municipi:"Castellnou dels Aspres",lat:42.61194,lon:2.69389,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat d'en Geli",wikidata:"Q16031948",source:"",alt_name:"Roc del Llamp"},
{name:"Dolmen del Coll de la Farella",municipi:"Cervera de la Marenda",lat:42.435,lon:3.12972,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Coll de la Farella",wikidata:"Q16031905",source:"",alt_name:""},
{name:"Dolmen de Coma Enestapera",municipi:"Cervera de la Marenda",lat:42.45167,lon:3.14333,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Coma Enestapera",wikidata:"Q16031910",source:"",alt_name:""},
{name:"La Pedra Dreta",municipi:"Cervera de la Marenda",lat:42.44167,lon:3.13528,hi_es:"SI",megalith_type:"menhir",wikipedia:"ca:La Pedra Dreta (Cervera)",wikidata:"Q28712064",source:"",alt_name:"Menhir de San Salvador"},
{name:"Dolmen de Rimbau",municipi:"Cotlliure",lat:42.50426,lon:3.05735,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Cabana del Moro",municipi:"Llauró",lat:42.55278,lon:2.75056,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Cabana del Moro (Llauró)",wikidata:"Q11350662",source:"",alt_name:""},
{name:"Dolmen de Galuert",municipi:"Llauró",lat:42.53445,lon:2.74584,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Galuert",wikidata:"Q16031920",source:"",alt_name:""},
{name:"Dolmen del Quadre",municipi:"Montesquiu d'Albera",lat:42.53111,lon:2.88472,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Menhir del Roc del Ram",municipi:"Oms",lat:42.545,lon:2.69611,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de La Creu de La Llosa",municipi:"Queixàs",lat:42.6342177,lon:2.6436346,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:""},
{name:"Dolmen del Fornàs",municipi:"Queixàs",lat:42.63194,lon:2.64056,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Fornàs",wikidata:"Q62128201",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:""},
{name:"Dolmen del Serrat d'en Jacques",municipi:"Queixàs",lat:42.635,lon:2.64611,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat d'en Jaques",wikidata:"Q62128276",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:""},
{name:"Balma del Moro",municipi:"La Roca d'Albera",lat:42.50094,lon:2.93944,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Balma del Moro",wikidata:"Q2881447",source:"",alt_name:""},
{name:"Menhir de la Roca d'Albera",municipi:"La Roca d'Albera",lat:42.53222,lon:2.92972,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:"Menhir de Laroque-des-Albères"},
{name:"Dolmen de l'Oliveda d'en David",municipi:"Salses",lat:42.87139,lon:2.94639,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Pla de les Arques",wikidata:"cau",source:"",alt_name:"Dolmen del Pla de les Arques"},
{name:"Dolmen del Serrat de les Fonts I",municipi:"Sant Marçal",lat:42.53861,lon:2.61056,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat de les Fonts I",wikidata:"Q62101542",source:"",alt_name:""},
{name:"Dolmen del Serrat de les Fonts II",municipi:"Sant Marçal",lat:42.53528,lon:2.60556,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat de les Fonts II",wikidata:"Q65205643",source:"",alt_name:""},
{name:"Dolmen del Castell",municipi:"Sant Miquel de Llotes",lat:42.39167,lon:2.36611,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Castell",wikidata:"Q65205639",source:"",alt_name:"Dolmen de Valltorta o de la Font del Bulès"},
{name:"Dolmen del Mas d'en Peirot I",municipi:"Sant Miquel de Llotes",lat:42.64278,lon:2.64028,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Mas d'en Peirot I",wikidata:"Q14627603",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:""},
{name:"Dolmen del Mas d'en Peirot II",municipi:"Sant Miquel de Llotes",lat:42.64278,lon:2.63861,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Mas d'en Peirot II",wikidata:"Q65205641",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:""},
{name:"Dolmen de les Molleres",municipi:"Sant Miquel de Llotes",lat:42.6425,lon:2.61139,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de les Molleres",wikidata:"Q65205638",source:"ca:Dòlmens de Sant Miquel de Llotes",alt_name:"Dolmen del Camp Gran I"},
{name:"Dolmen de la Creu del Senyal",municipi:"El Voló",lat:42.50667,lon:2.86,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Creu del Senyal",wikidata:"Q16031914",source:"",alt_name:""},
{name:"Balma de Na Cristiana",municipi:"L'Albera",lat:42.48444,lon:2.88722,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Balma de na Cristiana",wikidata:"Q1235839",source:"",alt_name:""},
{name:"Caixa de Rotllan",municipi:"Arles i Montboló",lat:42.4809614,lon:2.6008716,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Caixa de Rotllan",wikidata:"Q2933393",source:"",alt_name:""},
{name:"Menhir de la Dona Morta",municipi:"Els Banys d'Arles i Palaldà",lat:42.40908,lon:2.69596,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Canors",municipi:"Les Cluses",lat:42.49639,lon:2.84111,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Canors",wikidata:"Q20818108",source:"",alt_name:"Dolmen de les Saleres"},
{name:"Dolmen de la Siureda",municipi:"Morellàs i les Illes",lat:42.46306,lon:2.79139,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Siureda",wikidata:"Q3034111",source:"",alt_name:""},
{name:"Dolmen de Castelló",municipi:"Prats de Molló i la Presta",lat:42.41944,lon:2.46611,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Castelló",wikidata:"Q16031902",source:"",alt_name:""},
{name:"Dolmen del Camp d'en Serís",municipi:"Reiners",lat:42.50528,lon:2.69028,hi_es:"SI",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Camp d'en Serís",wikidata:"Q16031899",source:"",alt_name:""},
{name:"Dolmen de la Roira",municipi:"Ansinyà",lat:42.76194,lon:2.50722,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"Q16031950",source:"",alt_name:""},
{name:"Dolmen del Molí del Vent",municipi:"Bellestar",lat:42.72694,lon:2.60556,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Molí del Vent II",municipi:"Bellestar",lat:42.72871,lon:2.60678,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Cova del Misser",municipi:"Campossí",lat:42.67956,lon:2.45438,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Femna Mòrta (runes)",municipi:"Campossí",lat:42.6839981,lon:2.4340401,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Roc de l'Arca",municipi:"Felluns",lat:42.76278,lon:2.49667,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Cauna del Moro",municipi:"Felluns",lat:42.7625846,lon:2.4967664,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"Q16031944",source:"",alt_name:""},
{name:"Dolmen de les Apostades",municipi:"Trillà",lat:42.74861,lon:2.52056,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de les Colombines",municipi:"Trillà",lat:42.74861,lon:2.53167,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Guardiola",municipi:"Rodès",lat:42.6621263,lon:2.5489344,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Serrat Blanc",municipi:"Rodès",lat:42.6792976,lon:2.5364480,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Coll de la Creu",municipi:"Banyuls de la Marenda",lat:42.4583560,lon:3.1364097,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Coll de Tribes",municipi:"Eus",lat:42.6789226,lon:2.4095678,hi_es:"SI",megalith_type:"dolmen",wikipedia:"Fr:Dolmen du Coll del Tribe",wikidata:"Q16031908",source:"",alt_name:""},
{name:"Menhir de Counozouls",municipi:"Conòsols",lat:42.7294677,lon:2.2237590,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"Q22691590",source:"",alt_name:""},
{name:"Menhir de la Bassouse",municipi:"Eina",lat:42.4772581,lon:2.0709083,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Calcina",municipi:"Ansinyà",lat:42.7619019,lon:2.5163901,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen dels Planiols",municipi:"Arboçols",lat:42.6657906,lon:2.4654713,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Caladroer II (destruït)",municipi:"Caladroer",lat:42.7314796,lon:2.6557801,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de l'Arca de Calaons III",municipi:"Eus",lat:42.6573181,lon:2.4159200,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen Roca Flavia II",municipi:"Font-romeu, Odelló i Vià",lat:42.4850845,lon:2.0652907,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Llosa (en runes)",municipi:"Montalbà del Castell",lat:42.7126694,lon:2.5815599,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Coll de Jou",municipi:"Mosset",lat:42.6879698,lon:2.2506362,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de los Masos",municipi:"Los Masos",lat:42.6227989,lon:2.4627800,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Menhir de les Fumades",municipi:"Prats de Sornià",lat:42.74851,lon:2.46001,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Menhir de la Pedra Dreta",municipi:"Bellestar",lat:42.7276192,lon:2.6572499,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Pedra Dreta de l’Est",municipi:"Cervera de la Marenda",lat:42.4559115,lon:3.1589628,hi_es:"SI",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"https://www.megalithic.co.uk/article.php?sid=9670",alt_name:"Menhir Peyra Ficta"},
{name:"Menhir del Molí d'Eina",municipi:"Eina",lat:42.47722,lon:2.07083,hi_es:"SI",megalith_type:"menhir",wikipedia:"ca:Menhir del Molí d'Eina",wikidata:"Q62088275",source:"",alt_name:"Menhir del Pla del Bosc, menhir de la Bassouse"},
{name:"Dolmen dels Masos",municipi:"Els Masos",lat:42.62278,lon:2.46278,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Roca gravada de Glorianes",municipi:"Glorianes",lat:42.59083,lon:2.56361,hi_es:"SI",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"La Pedra Dreta",municipi:"Caladroer",lat:42.7275,lon:2.65722,hi_es:"SI",megalith_type:"menhir",wikipedia:"ca:Pedra Dreta (Caladroer)",wikidata:"Q16510080",source:"",alt_name:""},
{name:"Cista de les Fontetes",municipi:"Angostrina i Vilanova de les Escaldes",lat:42.48944,lon:1.97139,hi_es:"",megalith_type:"cist",wikipedia:"ca:Cista de les Fontetes ",wikidata:"Q62091912",source:"",alt_name:""},
{name:"Menhir d'Èguet",municipi:"Èguet",lat:42.50167,lon:2.01806,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Pujolet",municipi:"Èguet",lat:42.49917,lon:2.01778,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Pujolet",wikidata:"Q62096407",source:"",alt_name:""},
{name:"Hàbitat del Pla del Bac",municipi:"Eina",lat:42.47306,lon:2.07333,hi_es:"",megalith_type:"Hàbitat prehistòric",wikipedia:"ca:Hàbitat del Pla del Bac",wikidata:"Q62086500",source:"",alt_name:""},
{name:"Menhir del Coll de la Perxa",municipi:"Eina",lat:42.48333,lon:2.08833,hi_es:"",megalith_type:"menhir",wikipedia:"ca:Menhir del Coll de la Perxa",wikidata:"Q62086408",source:"",alt_name:""},
{name:"Pedra dels Traginers",municipi:"Eina",lat:42.48167,lon:2.06833,hi_es:"",megalith_type:"Pont megalític",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Pont megalític d'Eina",municipi:"Eina",lat:42.48222,lon:2.06889,hi_es:"",megalith_type:"Pont megalític",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Cista de Roca Flavià",municipi:"Font-romeu, Odelló i Vià",lat:42.48472,lon:2.06194,hi_es:"",megalith_type:"cist",wikipedia:"ca:Cista de Roca Flavià",wikidata:"Q62091412",source:"",alt_name:""},
{name:"Sepulcre megalític del Bac d'Amunt",municipi:"Font-romeu, Odelló i Vià",lat:42.48139,lon:2.05583,hi_es:"",megalith_type:"Sepulcre megalític",wikipedia:"ca:Sepulcre megalític del Bac d'Amunt",wikidata:"Q62091843",source:"",alt_name:""},
{name:"Menhir d'Odelló",municipi:"Font-romeu, Odelló i Vià",lat:42.50556,lon:2.04528,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Menhir de Llo",municipi:"Llo",lat:42.45583,lon:2.06444,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Menhir de Targasona",municipi:"Targasona",lat:42.49611,lon:1.99056,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"La Pedra Dreta",municipi:"Targasona",lat:42.49611,lon:1.98972,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Bruga",municipi:"Puigbalador",lat:42.65389,lon:2.09611,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Arca de la Portella",municipi:"Aiguatèbia i Talau",lat:42.55861,lon:2.18611,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Arca de la Portella",wikidata:"Q56401690",source:"",alt_name:""},
{name:"Dolmen del Montsec I",municipi:"Rià i Cirac",lat:42.62306,lon:2.38361,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen 1 del Montsec",wikidata:"Q51885144",source:"",alt_name:""},
{name:"Dolmen del Roc de l'Home Mort I",municipi:"Rià i Cirac",lat:42.63056,lon:2.37611,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen 1 del Roc de l'Home Mort",wikidata:"Q52146332",source:"",alt_name:""},
{name:"Dolmen de Boera",municipi:"Prada",lat:42.595,lon:2.43111,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Boera",wikidata:"Q51789651",source:"",alt_name:""},
{name:"Dolmen de la Barraca",municipi:"Tarerac",lat:42.67333,lon:2.51,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Barraca",wikidata:"Q11908237",source:"",alt_name:""},
{name:"Dolmen de la Bressa",municipi:"Molig",lat:42.67444,lon:2.38417,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Bressa",wikidata:"Q20819612",source:"",alt_name:""},
{name:"Dolmen de la Pineda",municipi:"Molig",lat:42.65889,lon:2.39806,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Pineda",wikidata:"Q56400546",source:"",alt_name:""},
{name:"Dolmen de la Portella",municipi:"Molig",lat:42.64611,lon:2.40889,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Portella",wikidata:"Q56400550",source:"",alt_name:""},
{name:"Dolmen de la Roca d'Arques",municipi:"Jújols",lat:42.58194,lon:2.30306,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Miralles",municipi:"Conat",lat:42.63611,lon:2.32944,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Miralles",wikidata:"Q20817422",source:"",alt_name:""},
{name:"Dolmen de Vilafranca de Conflent",municipi:"Vilafranca de Conflent",lat:42.58722,lon:2.36611,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Coll de Creu",municipi:"Clarà i Villerac",lat:42.60278,lon:2.45444,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Coll de Creu",wikidata:"Q51879071",source:"",alt_name:""},
{name:"Dolmen del Cortal del Polita",municipi:"Serdinyà",lat:42.5575,lon:2.31444,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Cortal del Polita",wikidata:"Q56400671",source:"",alt_name:""},
{name:"Dolmen del Roc d'Arques",municipi:"Orellà",lat:42.56417,lon:2.24,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Roc d'Arques",wikidata:"Q56401525",source:"",alt_name:""},
{name:"Dolmen del Roc de Jornac",municipi:"Orbanyà",lat:42.62861,lon:2.3275,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Roc de Jornac",wikidata:"Q52146280",source:"",alt_name:""},
{name:"Dolmen del Roc de les Creus",municipi:"Conat",lat:42.62833,lon:2.35972,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Roc de les Creus",wikidata:"Q52146296",source:"",alt_name:""},
{name:"Roca i Cúpules de Nabilles",municipi:"Rià i Cirac",lat:42.62694,lon:2.36111,hi_es:"",megalith_type:"cúpula",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Gratallops",municipi:"Banyuls de la Marenda",lat:42.44667,lon:3.12361,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Gratallops",wikidata:"Q16031921",source:"",alt_name:""},
{name:"Menhir de Perafita",municipi:"Banyuls de la Marenda",lat:42.46111,lon:3.15472,hi_es:"",megalith_type:"menhir",wikipedia:"ca:Menhir de Perafita",wikidata:"Q20819608",source:"",alt_name:""},
{name:"Dolmen de Moragues",municipi:"Bula d'Amunt",lat:42.595,lon:2.59083,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Moragues",wikidata:"Q20818713",source:"",alt_name:"Dolmen del Cortal d’en Vilar"},
{name:"Dolmen del Pla de les Eugues",municipi:"Bula d'Amunt",lat:42.585,lon:2.52611,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Pla de les Eugues",wikidata:"Q16511347",source:"",alt_name:""},
{name:"Estela de Bula d'Amunt",municipi:"Bula d'Amunt",lat:42.57944,lon:2.61389,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Arca de la Ginebrosa",municipi:"Caladroer",lat:42.72611,lon:2.65444,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Arca de la Ginebrosa",wikidata:"Q20819658",source:"",alt_name:""},
{name:"La Caixeta",municipi:"Cameles, ara a Corbera la Cabana",lat:42.65,lon:2.685,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:La Caixeta (Cameles)",wikidata:"Q11350791",source:"",alt_name:""},
{name:"Dolmen del Serrat d'en Poll",municipi:"Cameles",lat:42.645,lon:2.67444,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat d'en Poll",wikidata:"Q62267986",source:"",alt_name:""},
{name:"Dolmen de Vallcrosa",municipi:"Cameles",lat:42.64083,lon:2.68194,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Vallcrosa",wikidata:"Q62267855",source:"",alt_name:""},
{name:"Dolmen del Pla de l'Arca",municipi:"Castellnou dels Aspres",lat:42.59722,lon:2.68833,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Pla de l’Arca (Castellnou dels Aspres)",wikidata:"Q16031933",source:"",alt_name:""},
{name:"Dolmen del Solà dels Clots",municipi:"Castellnou dels Aspres",lat:42.59472,lon:2.70694,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Solà dels Clots",wikidata:"Q16031962",source:"",alt_name:""},
{name:"Dolmen del Roc d'en Coll",municipi:"Corbera",lat:42.64028,lon:2.65667,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Roc d'en Coll",wikidata:"Q62129122",source:"",alt_name:""},
{name:"Pedra Dreta de l'Aglí",municipi:"Espirà de l'Aglí",lat:0,lon:0,hi_es:"",megalith_type:"menhir",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Serrat de les Costes",municipi:"Llauró",lat:42.55222,lon:2.76528,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen del Serrat de les Costes",wikidata:"Q52161612",source:"",alt_name:""},
{name:"Pedra gravada de Perpinyà",municipi:"Perpinyà",lat:42.69917,lon:2.89833,hi_es:"",megalith_type:"stone",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de l'Arqueta",municipi:"Portvendres",lat:42.515,lon:3.12306,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de Mas Rimbaut",municipi:"Portvendres",lat:42.515,lon:3.12389,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen del Cementiri dels Moros",municipi:"Prunet i Bellpuig",lat:42.56611,lon:2.64611,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen d'en Ques",municipi:"Prunet i Bellpuig",lat:42.56694,lon:2.64611,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Ramera I",municipi:"Queixàs",lat:42.60611,lon:2.66806,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Ramera I",wikidata:"Q16031942",source:"",alt_name:""},
{name:"Dolmen de la Ramera II",municipi:"Queixàs",lat:42.60611,lon:2.66917,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Ramera II",wikidata:"Q20816969",source:"",alt_name:""},
{name:"La Pedra Escrita",municipi:"Queixàs",lat:42.635,lon:2.64611,hi_es:"",megalith_type:"stone",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de l'Oratori",municipi:"Sant Marçal",lat:42.53056,lon:2.60111,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de l'Oratori",wikidata:"Q16031930",source:"",alt_name:""},
{name:"Dolmen del Mas de l'Ocell, o del Camp Gran I",municipi:"Sant Miquel de Llotes",lat:42.39167,lon:2.36611,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Túmul de Pujols",municipi:"Talteüll",lat:42.82222,lon:2.73722,hi_es:"",megalith_type:"tumulus",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"La Caixa de l'Obra",municipi:"Tellet",lat:42.52694,lon:2.67111,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Caixa de l'Obra",wikidata:"Q11350706",source:"",alt_name:""},
{name:"Caixa del Moro",municipi:"Teulís",lat:42.51972,lon:2.6275,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Caixa del Moro",wikidata:"Q11350731",source:"",alt_name:""},
{name:"Dolmen de Ribes Roges",municipi:"Teulís",lat:42.51278,lon:2.62444,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Ribes Roges",wikidata:"Q16031943",source:"",alt_name:""},
{name:"Pedra Dreta del Planal de la Coma del Llop",municipi:"Vingrau",lat:42.83778,lon:2.81861,hi_es:"",megalith_type:"menhir",wikipedia:"ca:Pedra Dreta del Planal de la Coma del Llop",wikidata:"Q16510131",source:"",alt_name:""},
{name:"Dolmen dels Camps de les Pedres",municipi:"Cortsaví",lat:42.46778,lon:2.58028,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Caseta",municipi:"Cortsaví",lat:42.48667,lon:2.555,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de la Caseta",wikidata:"Q56402005",source:"",alt_name:""},
{name:"Dolmen del Pla del Castellar",municipi:"Cortsaví",lat:42.49083,lon:2.5675,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Cova d'en Rotllan",municipi:"Cortsaví",lat:42.48972,lon:2.57,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Cova d'en Rotllan",wikidata:"Q3001817",source:"",alt_name:""},
{name:"Dolmen de Formentera",municipi:"Montboló",lat:42.495,lon:2.63306,hi_es:"",megalith_type:"dolmen",wikipedia:"ca:Dolmen de Formentera",wikidata:"Q16031919",source:"",alt_name:""},
{name:"Pedra Gravada de Can Marc",municipi:"Prats de Molló i la Presta",lat:42.41944,lon:2.48583,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Pedra Gravada de les Garcies",municipi:"Prats de Molló i la Presta",lat:42.41083,lon:2.47222,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Font de l'Arca",municipi:"Campossí",lat:42.704080,lon:2.446080,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:"Dolmen de la Cabaneta des Très Pèiras, dolmen de Campossí"},
{name:"Tomba dels Espandiòls",municipi:"Maurí",lat:42.80389,lon:2.5525,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Roc de l'Arquet",municipi:"Planeses",lat:42.75694,lon:2.62889,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""},
{name:"Dolmen de la Mort de l'Eigassièr",municipi:"Trevillac",lat:42.73194,lon:2.515,hi_es:"",megalith_type:"dolmen",wikipedia:"",wikidata:"",source:"",alt_name:""}
];

